main: main.cpp
	g++ -Wall main.cpp -o main -lSOIL -lglut -lGL -lGLU 

rain : rain.cpp
	g++ rain.cpp -o rain -lglut -lGL -lGLU -lSOIL

car : car.cpp
	g++ car.cpp -o car -lSOIL -lglut -lGL -lGLU 

smoke : Smoke.cpp
	g++ Smoke.cpp -o smoke -lglut -lGL -lGLU -lSOIL